on:
  push:
    tags:
      - 'v*'

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:latest,${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:${{ github.ref_name}}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:buildcache,mode=max
