on:
  push:
    tags:
      - 'v*'

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:latest,${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:${{ github.ref_name}}
