name: Create a release

on:
  workflow_dispatch:

jobs:

  semver:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    outputs:
      tag_major: ${{ steps.get_tag.outputs.tag_major }}
      tag_minor: ${{ steps.get_tag.outputs.tag_minor }}
      tag: ${{ steps.get_tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get next semantic version
        id: get_tag
        run: |
          semver=$(npx semantic-release -b main -p -d | grep 'The next release' | awk '{print $NF}')
          echo "::set-output name=tag_major::v"$(echo "$semver" | awk -F \. {'print $1'})
          echo "::set-output name=tag_minor::v"$(echo "$semver" | awk -F \. {'print $1"."$2'})
          echo "::set-output name=tag::v"$(echo "$semver")

      - name: Debug tag name
        run: |
          echo ${{ steps.get_tag.outputs.tag_major }}
          echo ${{ steps.get_tag.outputs.tag_minor }}
          echo ${{ steps.get_tag.outputs.tag }}

  build-push:
    needs: semver
    if: ${{ needs.semver.outputs.tag }}
    runs-on: ubuntu-latest
    env:
      IMAGE_MAJOR_TAG: ${{ needs.semver.outputs.tag_major }}
      IMAGE_MINOR_TAG: ${{ needs.semver.outputs.tag_minor }}
      IMAGE_TAG: ${{ needs.semver.outputs.tag }}

    steps:
      - name: Checkout Release Tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:latest
            ${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:${{ env.IMAGE_MAJOR_TAG }}
            ${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:${{ env.IMAGE_MINOR_TAG }}
            ${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_LOGIN }}/symfony-gh-actions:buildcache,mode=max

  create_release:
    needs: [semver, build-push]
    if: ${{ needs.semver.outputs.tag }}
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.semver.outputs.tag }}

    steps:
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.IMAGE_TAG }}
          generate_release_notes: true
